from enum import StrEnum


class IdentityErrorCode(StrEnum):
    USER_NOT_FOUND = "USER_NOT_FOUND"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    INACTIVE_USER = "INACTIVE_USER"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    INSUFFICIENT_ROLE = "INSUFFICIENT_ROLE"
    CANNOT_MANAGE_USER = "CANNOT_MANAGE_USER"
    INVALID_EMAIL = "INVALID_EMAIL"
    PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT"
    PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG"


class CannotManageUserReason(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    SELF = "SELF"
